import { defineConfig, presetUno, presetIcons, presetTypography } from 'unocss'

export default defineConfig({
  presets: [
    presetUno(),
    presetIcons({
      scale: 1.4,
      warn: true,
      extraProperties: {
        'display': 'inline-block',
        'flex-shrink': '0',
      },
    }),
    presetTypography(),
  ],
  safelist: [
    'i-lucide-clipboard-list',
    'i-lucide-book-open',
    'i-lucide-settings',
    'i-lucide-x',
    'i-lucide-plus',
    'i-lucide-grip-vertical',
    'i-lucide-chevron-right',
    'i-lucide-chevron-down',
    'i-lucide-arrow-left',
    'i-lucide-tag',
    'i-lucide-upload',
    'i-lucide-alert-triangle',
    'i-lucide-alert-circle',
    'i-lucide-clock',
    'i-lucide-pencil',
    'i-lucide-eye',
    'i-lucide-check-circle',
    'i-lucide-list',
    'i-lucide-quote',
    'i-lucide-code-xml',
    'i-lucide-table',
    'i-lucide-image',
    'i-lucide-loader-2',
    'i-lucide-undo-2',
    'i-lucide-redo-2',
    'i-lucide-arrow-up-to-line',
    'i-lucide-arrow-down-to-line',
    'i-lucide-arrow-left-to-line',
    'i-lucide-arrow-right-to-line',
    'i-lucide-trash-2',
    'i-lucide-table-2',
    'i-lucide-table-cells-merge',
    'i-lucide-table-cells-split',
    'i-lucide-link',
    'i-lucide-bookmark',
  ],
  shortcuts: {
    'btn': 'px-4 py-2 rounded-lg cursor-pointer inline-flex items-center gap-2 transition-colors disabled:cursor-not-allowed disabled:opacity-50 disabled:pointer-events-none',
    'btn-primary': 'btn bg-blue-600 text-white hover:bg-blue-700',
    'btn-secondary': 'btn bg-gray-200 text-gray-700 hover:bg-gray-300',
    'btn-danger': 'btn bg-red-600 text-white hover:bg-red-700',
    'card': 'bg-white rounded-xl shadow-sm border border-gray-200 p-6',
    'input': 'w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent',
    'textarea': 'w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-y min-h-[80px]',
    'label': 'text-sm font-medium text-gray-700 mb-1 block',
  },
})
